### ISSUE TITLE
Refactor xml files with documentation

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/MapClass#5]
The main file is `mapclass.xml` and it includes `introo.xml`. The other two files are `chapter2.xml` and `intro.xml` are not linked anywhere and they seem to be earlier started and then subsequently copied elsewhere versions of text.

**Comment by olexandr-konovalov** [comment]
@shpectorov any advice on this? Should those unlinked files be deleted?

**Comment by shpectorov** [comment]
@alex-konovalov I removed the two files and also renamed the old file introo.xml as intro.xml (and
corrected accordingly the link in mapclass.xml). Not sure how to check consistency of the present version...

**Comment by olexandr-konovalov** [comment]
Are you able to read into GAP `makedoc.g` file and build the manual?

**Comment by shpectorov** [comment]
The only GAP I have under UNIX does not work (shows an error on loading) and needs to be upgraded. 
This will take some time, as it must be done via the IT services.

**Comment by olexandr-konovalov** [comment]
I've checked myself - the manual builds. Did not inspect the content though.

Also, I am not familiar with your setup, but installing GAP does not require admin password provided you have dependencies installed. That's exactly to cater for situations like that.

**Comment by olexandr-konovalov** [comment]
This is now fixed in version 1.4.4
