### ISSUE TITLE
dead website link

### ISSUE THREAD

**Issue by videlec** [gap-packages/MapClass#6]
The following url http://web.mat.bham.ac.uk/~jamesa/mapclass/ is dead (Error 404 on Feb 18th 2018).

**Comment by olexandr-konovalov** [comment]
Thank you @videlec - we know about this and the plan is to make a new release and host the new webpage on github pages. So this issue is a part of https://github.com/gap-packages/MapClass/issues/4

**Comment by olexandr-konovalov** [comment]
P.S. The package page on the GAP site is http://www.gap-system.org/Packages/mapclass.html
